export const PROJECTS_REQUESTED = 'PROJECTS_REQUESTED';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';

export const PROJECT_INFO_REQUESTED = 'PROJECT_INFO_REQUESTED';
export const FETCH_PROJECT_INFO_SUCCESS = 'FETCH_PROJECT_INFO_SUCCESS';
export const FETCH_PROJECT_INFO_FAILURE = 'FETCH_PROJECT_INFO_FAILURE';
